---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(knitr)
library(janitor)
library(tinytex)
library(kableExtra)
library(ggplot2)
library(scales)
```


```{r, message=FALSE}
annualTickets <- read_csv("C:/Users/yingy/Downloads/archive/AnnualTicketSales.csv")
TopGenres <- read_csv("C:/Users/yingy/Downloads/archive/TopGenres.csv")
popularCreative <- read_csv("C:/Users/yingy/Downloads/archive/PopularCreativeTypes.csv")

```


```{r eval=FALSE, include=FALSE}
esquisse::esquisser(viewer = "browser")
```

```{r}
colnames(TopGenres)[4] <- "TOTAL.GROSS"
TopGenres$`TOTAL.GROSS` <- gsub("\\$","",TopGenres$`TOTAL.GROSS`)
TopGenres$`TOTAL.GROSS` <- gsub(",","",TopGenres$`TOTAL.GROSS`)
TopGenres$`TOTAL.GROSS` <- as.numeric(TopGenres$`TOTAL.GROSS`)

# Reorder GENRES based on TOTAL.GROSS
TopGenres$GENRES <- factor(TopGenres$GENRES, 
                            levels = TopGenres$GENRES[order(TopGenres$TOTAL.GROSS, decreasing = TRUE)])

# Create a bar plot using ggplot with reordered GENRES
ggplot(TopGenres, aes(x = GENRES, y = TOTAL.GROSS)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "Genres", y = "Total Gross in Billions $",
       title = "Most Popular Genres based on Earnings") +
  scale_y_continuous(n.breaks = 7, labels = label_comma()) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme_minimal() 
```


```{r, message=FALSE, warning=FALSE}
topDistributors <- read_csv("C:/Users/yingy/Downloads/archive/TopDistributors.csv") # load data set into the environment 
topDistributors <- topDistributors[-c(7,8,9,10),] # delete the rows not focused on
glimpse(topDistributors)

# convert total gross and average gross to integers 
topDistributors$`TOTAL GROSS` <-  gsub("\\$", "", topDistributors$`TOTAL GROSS`) 
topDistributors$`TOTAL GROSS` <-  gsub(",", "", topDistributors$`TOTAL GROSS`) 
topDistributors$`TOTAL GROSS` <- as.numeric(topDistributors$`TOTAL GROSS`)
topDistributors$`AVERAGE GROSS` <-  gsub("\\$", "", topDistributors$`AVERAGE GROSS`) 
topDistributors$`AVERAGE GROSS` <-  gsub(",", "", topDistributors$`AVERAGE GROSS`) 
topDistributors$`AVERAGE GROSS` <- as.numeric(topDistributors$`AVERAGE GROSS`)

topDistributors <- topDistributors %>% 
  mutate(TOTAL_GROSS_in_Billion = `TOTAL GROSS`/1000000000) %>% 
  mutate(AVERAGE_GROSS_in_Million = `AVERAGE GROSS`/1000000)
  

pie(topDistributors$`MOVIES`, labels = topDistributors$DISTRIBUTORS)
pie(topDistributors$`TOTAL GROSS`, labels = topDistributors$DISTRIBUTORS)


ggplot(topDistributors) +
  aes(
    x = MOVIES,
    y = TOTAL_GROSS_in_Billion,
    colour = DISTRIBUTORS,
    size = AVERAGE_GROSS_in_Million
  ) +
  geom_point(shape = "circle") + # create the scatter plot
  scale_color_hue(direction = 1) +
  labs(title = "Movie Release vs. Total Gross", color = "Distributors", size = "Average Gross in Million of Dollars") + # add the title and change the label for x and y axis
  xlab("\nMovie") +
  ylab("Total Gross in Billion of Dollars\n") +
  scale_x_continuous(n.breaks = 5, limits = c(400, 900)) +
  scale_y_continuous(n.breaks = 5, limits = c(20, 45), labels = label_comma()) +
  scale_size_continuous(labels = label_comma(), limits = c(35, 70)) +
  theme_light() +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  theme(
    plot.title = element_text(size = 15L,
    face = "italic",
    hjust = 0.5),
    axis.title.y = element_text(size = 12L),
    axis.title.x = element_text(size = 12L),
    legend.text = element_text(size = 10), 
    legend.title = element_text(size = 10),
    legend.key.height = unit(0.5, 'cm'),
    legend.key.width = unit(1.5, 'cm')
  )

```


Box Office Mojo by IMDbPro considers a movie in wide release or about to go wide when it is playing at 600 or more theaters, which generally indicates a nationwide release (the term is short for "nationwide").

```{r, message=FALSE}
wideRelease <- read_csv("C:/Users/yingy/Downloads/archive/WideReleasesCount.csv") # load data set into environment
wideRelease <- wideRelease[,-c(8,9,10)] # delete other companies

wideRelease_long <- wideRelease %>% # convert to the Year, Company, Release form 
  pivot_longer(!`YEAR`, names_to = c("Company"), values_to = "Release")

wideRelease_totalNumber <- wideRelease_long %>% # summarize the total number of wide release for each company from 1995 to 2021
  group_by(Company) %>% 
  summarise(`Wide Release` = sum(Release))
wideRelease_totalNumber$Company <- str_to_title(wideRelease_totalNumber$Company) # change the format of company name 
wideRelease_totalNumber$Company[6] <- "Warner Bros."
wideRelease_totalNumber$`Total Release` <- topDistributors$MOVIES[match(wideRelease_totalNumber$Company, topDistributors$DISTRIBUTORS)] # add the total number of release from the top Distributor data set 

wideRelease_totalNumber <- wideRelease_totalNumber %>% # calculate the percentage of wide release movie out of total release
  mutate(Percentage = `Wide Release`/`Total Release`)

ggplot(wideRelease_totalNumber) +
  aes(x = Company, y = Percentage) +
  geom_col(fill = "#112446") +
  labs(
    title = "Percentage of Wide Release Movie Out of Total Release"
  ) +
  theme_gray() +
  theme(
    plot.title = element_text(size = 15L,
    face = "italic",
    hjust = 0.5)
  )

wideRelease <- read_csv("C:/Users/yingy/Downloads/archive/WideReleasesCount.csv") # load data set into environment
wideRelease <- wideRelease[,-c(8,10)] # delete other companies

summary <- wideRelease %>% 
  adorn_totals(where = c("row", "col") ) %>%
  adorn_percentages(denominator = "all") %>%
  adorn_pct_formatting(digits = 2) %>%
  adorn_title(
    placement = "combined",
    row_name = "Year",
    col_name = "Company")

format <- attr(summary, "core") %>%
  adorn_totals(where = c("row", "col")) %>%
  mutate(
    across(.cols = where(is.numeric),
           .fns = ~format(.x, big.mark = ","))
  )
wideReleaseFreqTab <- summary %>%
  adorn_ns(position = "front", ns = format)


wideReleaseFreqTab %>%
  kable(
    caption = "<center>Year and Number of Wide Release for Company<center>",
    booktabs = TRUE,
    align = c("c", rep("c", 6))
  ) %>%
  kableExtra::kable_styling(
    bootstrap_options = c("striped"),
    font_size = 12
  )

ggplot(wideRelease_long) +
  aes(x = YEAR, y = Release) +
  labs(title = "Year vs. Release") +
  xlab("\nYear") +
  geom_line(colour = "#112446") +
  theme_light() +
  theme(plot.title = element_text(size = 15L,
        face = "italic",
        hjust = 0.5)) +
  facet_grid(vars(), vars(Company))

```



```{r, warning=FALSE, message=FALSE}
highestGrossers <- read_csv("C:/Users/yingy/Downloads/archive/HighestGrossers.csv")
glimpse(highestGrossers)

highestGrossers$`TOTAL IN 2019 DOLLARS` <-  gsub("\\$", "", highestGrossers$`TOTAL IN 2019 DOLLARS`) 
highestGrossers$`TOTAL IN 2019 DOLLARS` <-  gsub(",", "", highestGrossers$`TOTAL IN 2019 DOLLARS`) 
highestGrossers$`TOTAL IN 2019 DOLLARS` <- as.numeric(highestGrossers$`TOTAL IN 2019 DOLLARS`)

ggplot(highestGrossers) +
  aes(
    x = YEAR,
    y = MOVIE,
    colour = DISTRIBUTOR,
    size = `TOTAL IN 2019 DOLLARS`
  ) +
  geom_point(shape = "circle") +
  scale_color_hue(direction = 1) +
  labs(title = "Top Distributors From 1995 to 2021") +
  theme_gray() +
  theme(
    plot.title = element_text(size = 15L,
    face = "italic",
    hjust = 0.5)
  )

ggplot(highestGrossers) +
  aes(x = DISTRIBUTOR) +
  geom_bar(fill = "#25324A") +
  labs(title = "Highest Grossers vs. Distributors") +
  xlab("\nDistributor") +
  scale_y_continuous(n.breaks = 12, limits = c(0, 12)) +
  theme_grey() +
  theme(
    plot.title = element_text(size = 15L,
    face = "italic",
    hjust = 0.5)
  )

gross_movie <- lm(`TOTAL GROSS` ~ MOVIES + `AVERAGE GROSS`, data = topDistributors)
summary(gross_movie)
```

